### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by reftel** [jenkinsci/workflow-remote-loader-plugin#22]
### What feature do you want to see added?

PR #17 was merged a while ago. It would be very useful to have a release that includes it.

**Comment by Chris-Softrams** [comment]
Build failed - https://github.com/jenkinsci/workflow-remote-loader-plugin/runs/4503128036

Any updates?

**Comment by MarkEWaite** [comment]
https://github.com/jenkinsci/workflow-remote-loader-plugin/releases/tag/workflow-remote-loader-1.6 is now available from the Jenkins update center.

I strongly recommend that users switch to the more widely used and more actively maintained [Pipeline: Groovy Libraries](https://plugins.jenkins.io/pipeline-groovy-lib/) plugin.  I released a new version of this plugin because I was worried about the outdated versions of JGit, Groovy, and other jar files that were included in the plugin.  I do not plan to perform any significant additional maintenance on this plugin.
